create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.music_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  title text not null,
  created_at timestamptz not null default now()
);

alter table public.guestbook enable row level security;
alter table public.music_requests enable row level security;

drop policy if exists "guestbook_read" on public.guestbook;
create policy "guestbook_read" on public.guestbook for select to anon using (true);

drop policy if exists "guestbook_insert" on public.guestbook;
create policy "guestbook_insert" on public.guestbook for insert to anon with check (char_length(name) between 1 and 40 and char_length(message) between 1 and 500);

drop policy if exists "music_read" on public.music_requests;
create policy "music_read" on public.music_requests for select to anon using (true);

drop policy if exists "music_insert" on public.music_requests;
create policy "music_insert" on public.music_requests for insert to anon with check (char_length(name) between 1 and 40 and char_length(title) between 1 and 120);
